replicaCount: 4

image:
  repository: us-central1-docker.pkg.dev/airis-artifacts/packages/data-loader
  tag: "2026-03-09-T-04-02-07_alpha_9a381a9"

env:
  REACT_APP_WS_BASE_URL: "webapp-api-server.default.svc.cluster.local:8083/ws"
  APPWRITE_BASE_ENDPOINT: "http://app.ramazzotti.raven.gdn/v1"
  APPWRITE_HOSTNAME: "app.ramazzotti.raven.gdn"
  FS_APPWRITE_ENDPOINT: "http://appwrite.default.svc.cluster.local/v1"
  APPWRITE_PROJECT_ID: "airis"
  APPWRITE_DATABASE_ID: "airisdb"
  APPWRITE_COLLECTION_ID: "videos"
  MAILBOX_UPLOAD_BUCKET: "airis-results-ramazzotti"
  FS_PREFIX: "gs://"

envFromSecrets:
  - secretName: appwrite-api-key
    keys:
      - APPWRITE_API_KEY
  - secretName: mapbox-api-key
    keys:
      - REACT_APP_MAPBOX_API_KEY

resources:
  limits:
    cpu: 0.5
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 1Gi

service:
  port: 8000
  portName: http

serviceAccount:
  name: airis
