replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/airis-artifacts/packages/geolocation
  tag: "2026-03-09-T-04-02-07_alpha_9a381a9"

env:
  SHARED_VOLUME: "/data"
  LD_LIBRARY_PATH: "/usr/local/nvidia/lib64"
  BENTOML_DO_NOT_TRACK: "True"
  TIMEOUT: "1500"
  LOGGER_CONFIG_PATH: "/home/bentoml/bento/src/airisml_logger_config_new.yaml"
  TORCH_HOME: "/home/bentoml/.cache/"
  DATABASE_PATH: "gs://airis-pocs/geolocation/robusta/assets/"
  REFERENCE_CONFIG__HOST: "robusta.geo-vector.services.com"
  EMBEDDING_MODEL_PARAMS__MODEL_TYPE: "megaloc"
  RERANKING_CONFIG__APPLY_RERANKING: "False"
  EMBEDDING_MODEL_PARAMS__FC_OUTPUT_DIM: "8448"
  AWS_DEFAULT_REGION: "il-central-1"
  GOOGLE_APPLICATION_CREDENTIALS: "/secrets/gs-secret.json"
  DIMENSIONALITY_REDUCTION_MODEL_PATH: "/models/geo/dimensionality_reduction"

resources:
  limits:
    cpu: 1.5
    memory: 5Gi
    nvidia.com/gpu: 1
  requests:
    cpu: 1.5
    memory: 5Gi
    nvidia.com/gpu: 1

gpu:
  enabled: true
  nodeSelector:
    node_pool: gpu-node-pool
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "airis-labs.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
  ldLibraryPath: "/usr/local/nvidia/lib64"

postman:
  image:
    repository: "us-central1-docker.pkg.dev/airis-artifacts/packages/postman"
    tag: "2026-03-09-T-04-02-07_alpha_9a381a9"
  env:
    JOB_TYPE: "geolocation"
    SHARED_VOLUME: "/data"
    POST_OFFICE_URL: "http://post-office.default.svc.cluster.local:2704"
    INFERENCE_URL: "http://localhost:3000/infer"
    IS_API: "True"
    SLEEP_TIME: "1"
    MONITOR_FLAG: "True"
    TIMEOUT: "550"
    SHOULD_UPLOAD_DIR: "false"
    GOOGLE_APPLICATION_CREDENTIALS: "/secrets/gs-secret.json"
  extraVolumeMounts:
    - name: gs-secret
      mountPath: /secrets
      readOnly: true

service:
  port: 3000

podAnnotations:
  gke-gcsfuse/volumes: "true"
  gke-gcsfuse/cpu-limit: "0"
  gke-gcsfuse/memory-limit: "0"
  gke-gcsfuse/ephemeral-storage-limit: "0"

assetsPvc:
  enabled: true
  claimName: "assets-pvc"
  mountPath: "/home/ubuntu/airis/ai/geo/assets"
  subPath: "airis-environment-assets/geolocation/assets/"
  readOnly: true

initContainers:
  - name: download-logging-config
    image: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    command: ["sh", "-c"]
    args:
      - |
        gcloud storage cp gs://airis-pocs/logging/airisml_logger_config_new.yaml /logging/airisml_logger_config_new.yaml
    env:
      GOOGLE_APPLICATION_CREDENTIALS: "/secrets/gs-secret.json"
    volumeMounts:
      - name: logging
        mountPath: /logging
      - name: gs-secret
        mountPath: /secrets
        readOnly: true

extraVolumes:
  - name: gs-secret
    secret:
      secretName: gs-secret
      items:
        - key: gs-secret.json
          path: gs-secret.json
  - name: logging
    emptyDir: {}

extraVolumeMounts:
  - name: logging
    mountPath: /home/bentoml/bento/src/airisml_logger_config_new.yaml
    subPath: airisml_logger_config_new.yaml

serviceAccount:
  name: airis
