apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                # Go over all environmets that have a config.yaml file
                - git:
                    repoURL: "https://github.com/yoav-test/gitops-poc.git"
                    revision: main
                    files:
                      - path: environments/**/config.yaml
                    pathParamPrefix: env
                    values:
                      env_name:  "{{ index .env.path.segments 1 }}"

                # Go over all services that have a chart-config.yaml file
                - git:
                    repoURL: "https://github.com/yoav-test/gitops-poc.git"
                    revision: main
                    files:
                      - path: services/**/chart-config.yaml
                    pathParamPrefix: app

          # Go over all services that have a values.yaml file for the given environment
          - git:
              repoURL: "https://github.com/yoav-test/gitops-poc.git"
              revision: main
              files:
                - path: "{{ .app.path.path }}/envs/{{ .env.path.basename }}/values.yaml"

  template:
    metadata:
      name: "{{ .app.path.basename }}-{{ .values.env_name }}"
    spec:
      project: '{{.values.env_name}}'
      sources:
        - repoURL: https://github.com/yoav-test/gitops-poc.git
          targetRevision: main
          ref: values
        - repoURL: '{{ .chart.repoURL }}'
          targetRevision: '{{ .chart.targetRevision }}'
          path: '{{.chart.path}}'
          helm:
            valueFiles:
              - "$values/{{ .app.path.path }}/envs/{{ .env.path.basename }}/values.yaml"
      destination:
        name: '{{ .cluster.name }}'
        namespace: '{{ .cluster.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
