replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/airis-artifacts/packages/geolocation-service
  tag: "2026-03-09-T-04-02-07_alpha_9a381a9"

env:
  DATABASE_HOST: "general-postgres.default.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "postgres"

resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 1
    memory: 512Mi

service:
  port: 61725
  portName: http

serviceAccount:
  name: airis
